[server]
headless = true
enableCORS = true
address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#005F9E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"